config/routes.rb
Rails.application.routes.draw do
  resources :campaigns

  resources :campaign_media

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :campaign_media
end

app/models/campaign_medium.rb
class CampaignMedium < ActiveRecord::Base
  belongs_to :campaign
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaign_media_controller.rb
class CampaignMediaController < ApplicationController
  before_action :set_campaign_medium, only: [:show, :edit, :update, :destroy]

  # GET /campaign_media
  # GET /campaign_media.json
  def index
    @campaign_media = CampaignMedium.all
  end

  # GET /campaign_media/1
  # GET /campaign_media/1.json
  def show
  end

  # GET /campaign_media/new
  def new
    @campaign_medium = CampaignMedium.new
  end

  # GET /campaign_media/1/edit
  def edit
  end

  # POST /campaign_media
  # POST /campaign_media.json
  def create
    @campaign_medium = CampaignMedium.new(campaign_medium_params)

    respond_to do |format|
      if @campaign_medium.save
        format.html { redirect_to @campaign_medium, notice: 'Campaign medium was successfully created.' }
        format.json { render :show, status: :created, location: @campaign_medium }
      else
        format.html { render :new }
        format.json { render json: @campaign_medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_media/1
  # PATCH/PUT /campaign_media/1.json
  def update
    respond_to do |format|
      if @campaign_medium.update(campaign_medium_params)
        format.html { redirect_to @campaign_medium, notice: 'Campaign medium was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign_medium }
      else
        format.html { render :edit }
        format.json { render json: @campaign_medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaign_media/1
  # DELETE /campaign_media/1.json
  def destroy
    @campaign_medium.destroy
    respond_to do |format|
      format.html { redirect_to campaign_media_url, notice: 'Campaign medium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_medium
      @campaign_medium = CampaignMedium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_medium_params
      params.require(:campaign_medium).permit(:name, :campaign_id)
    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params[:campaign]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_media_helper.rb
module CampaignMediaHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaign_media/_form.html.erb
<%= form_for @campaign_medium, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  campaign_media_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/campaign_media/edit.html.erb
<%- model_class = CampaignMedium -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => CampaignMedium %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaign_media/index.html.erb
<%- model_class = CampaignMedium -%>
<div class="page-header">
  <h1><%=t '.title', :default => CampaignMedium %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @campaign_media.each do |campaign_medium| %>
      <tr>
        <td><%= campaign_medium.id %></td>
        <td><%= campaign_medium.name %></td>
        <td><%=l campaign_medium.created_at, format: :long %></td>
        <td>
          <%= link_to campaign_medium_path(campaign_medium), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to campaign_medium_path(campaign_medium), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_campaign_medium_path,
            :class => 'btn btn-primary' %>

app/views/campaign_media/new.html.erb
<%- model_class = CampaignMedium -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => CampaignMedium %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaign_media/show.html.erb
<%- model_class = CampaignMedium -%>
<div class="page-header">
  <h1><%=t '.title', :default => CampaignMedium %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @campaign_medium.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              campaign_media_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_campaign_medium_path(@campaign_medium), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              campaign_medium_path(@campaign_medium),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/campaigns/_form.html.erb
<%= form_for @campaign, :html => { :class => 'form-horizontal form-model' } do |f| %>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  campaigns_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Campaign %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaigns/index.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => Campaign %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.id %></td>
        <td><%=l campaign.created_at, format: :long %></td>
        <td>
          <%= link_to campaign_path(campaign), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to campaign_path(campaign), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_campaign_path,
            :class => 'btn btn-primary' %>

app/views/campaigns/new.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Campaign %></h1>
</div>
<%= render :partial => 'form' %>

app/views/campaigns/show.html.erb
<%- model_class = Campaign -%>
<div class="page-header">
  <h1><%=t '.title', :default => Campaign %></h1>
</div>

<div class="fieldset">
  <dl>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              campaigns_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_campaign_path(@campaign), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              campaign_path(@campaign),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestHasMany</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>